version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh /app/docker/start_app.sh
    ports:
      - "8080:3000"
    volumes:
      - ".:/app"
      - yarn:/yarn
      - node_modules:/app/node_modules
    tty: true
volumes:
  yarn:
  node_modules:
